#!/usr/bin/env bash
# Displaying "bad luck" i=4 "good luck" i=8 "Best School" for other i value

i=1
while [ $i -le 10 ]
do
  if [ "$i" == 4 ]
  then
    echo "bad luck"
  elif [ "$i" == 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
