#!/usr/bin/env bash
#update the ip of loopback and facebook.com in the /etc/hosts file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2			localhost" > ~/hosts.new
echo "8.8.8.8			facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
